import { useGameState } from '../app/useGameState'
import { useGameCommands } from '../app/useGameCommands'
import { useGameUiState } from './hooks/useGameUiState'
import { CardHistoryPanel } from './panels/CardHistoryPanel'
import { BattleInfoPanel } from './panels/BattleInfoPanel'
import { UnitDetailPanel } from './panels/UnitDetailPanel'
import { Battlefield } from './battlefield/Battlefield'
import { TopStatusBar } from './hud/TopStatusBar'
import { BottomActionBar } from './hud/BottomActionBar'
import { CardSelectionOverlay } from './cards/CardSelectionOverlay'
import { ToastRegion } from './feedback/ToastRegion'
import { RunResultOverlay } from './feedback/RunResultOverlay'
import { cloneCost } from '../game/domain/rules/economy-rules'
export function GameScreen(){const {run,notifications}=useGameState(),dispatch=useGameCommands(),ui=useGameUiState();const selected=run.units.find(unit=>unit.id===ui.selectedUnitId);const cards=run.phase==='card-selection'||run.phase==='item-targeting';return <main className="game-shell"><CardHistoryPanel cards={run.cards} rerolls={run.rerolls}/><section className="center-stage"><TopStatusBar count={run.enemies.length}/><Battlefield units={run.units} enemies={run.enemies} projectiles={run.projectiles} selectedId={ui.selectedUnitId} onSelect={ui.setSelectedUnitId} onDrop={(sourceSlot,targetSlot)=>dispatch({type:'MOVE_OR_MERGE',sourceSlot,targetSlot})}/><BottomActionBar credits={run.credits} cost={cloneCost(run.successfulCloneCount)} next={cloneCost(run.successfulCloneCount+1)} tickets={run.freeCloneTickets} disabled={cards||run.phase==='victory'||run.phase==='defeat'} onClone={()=>dispatch({type:'CLONE_UNIT'})}/><ToastRegion notification={notifications[0]}/></section><aside className="right-column"><BattleInfoPanel run={run} onStart={()=>dispatch({type:'START_ROUND'})} onSkip={()=>dispatch({type:'SKIP_ROUND'})} onOpenCards={()=>ui.setOverlayVisible(true)}/><UnitDetailPanel unit={selected} onDiscard={()=>selected&&dispatch({type:'DISCARD_UNIT',unitId:selected.id})}/></aside>{cards&&ui.overlayVisible&&<CardSelectionOverlay offer={run.cardOffer} highlighted={ui.highlightedCard as never} itemTargeting={run.phase==='item-targeting'} units={run.units} rerolls={run.rerolls} onHighlight={id=>ui.setHighlightedCard(id)} onApply={()=>ui.highlightedCard&&dispatch({type:'CHOOSE_CARD',cardId:ui.highlightedCard as never})} onReroll={()=>dispatch({type:'REROLL_CARDS'})} onClose={()=>ui.setOverlayVisible(false)} onEquip={unitId=>dispatch({type:'EQUIP_PENDING_ITEM',unitId})}/>}<RunResultOverlay run={run} onReset={()=>dispatch({type:'RESET_RUN'})}/></main>}
