import type { GameStoreState } from './game-store-state'
import type { GameAction } from './game-action'
import { createInitialState } from './create-initial-state'
import { cloneUnit } from './commands/clone-unit'
import { resolveBoardDrop } from './commands/resolve-board-drop'
import { discardUnit } from './commands/discard-unit'
import { stepCombat } from '../simulation/step-combat'
import { offerCards } from '../simulation/round-resolution-system'
import { roundDefinition } from '../domain/rules/round-rules'
import { cardDefinitions } from '../config/card-definitions'
import { notificationMessage, type NotificationCode } from './notification'
import type { RunState } from '../domain/run-state'
import { seededRandomGenerator } from '../infrastructure/seeded-random-generator'
const notify=(state:GameStoreState,code:NotificationCode,payload:Record<string,string|number>={})=>({...state,notifications:[...state.notifications,{id:state.run.entityCounters.projectile+state.run.entityCounters.unit+state.notifications.length+1,code,message:notificationMessage(code,payload)}].slice(-5)})
const allowed=(phase:string,action:string)=>({ready:['START_ROUND','CLONE_UNIT','MOVE_OR_MERGE','DISCARD_UNIT','RESET_RUN','ACKNOWLEDGE_NOTIFICATION'],combat:['TICK','CLONE_UNIT','MOVE_OR_MERGE','DISCARD_UNIT','SKIP_ROUND','RESET_RUN','ACKNOWLEDGE_NOTIFICATION'],'card-selection':['CHOOSE_CARD','REROLL_CARDS','RESET_RUN','ACKNOWLEDGE_NOTIFICATION'],'item-targeting':['EQUIP_PENDING_ITEM','RESET_RUN','ACKNOWLEDGE_NOTIFICATION'],victory:['RESET_RUN','ACKNOWLEDGE_NOTIFICATION'],defeat:['RESET_RUN','ACKNOWLEDGE_NOTIFICATION']}[phase]||[]).includes(action)
export const gameReducer=(state:GameStoreState,action:GameAction):GameStoreState=>{if(!allowed(state.run.phase,action.type))return action.type==='TICK'?state:notify(state,'interaction-locked');switch(action.type){case 'RESET_RUN':return createInitialState(action.seed??seededRandomGenerator.next(state.run.randomSeed).seed);case 'ACKNOWLEDGE_NOTIFICATION':return {...state,notifications:state.notifications.slice(1)};case 'START_ROUND':{const d=roundDefinition(state.run.round.number);let run:RunState={...state.run,phase:'combat',round:{...state.run.round,kind:d.kind,remaining:d.duration,started:true,total:d.total},pendingSpawns:d.total};if(d.kind==='boss'){const id=run.entityCounters.enemy+1;run={...run,pendingSpawns:0,enemies:[...run.enemies,{id,definitionId:'alpha',hp:3200,maxHp:3200,trackDistance:0,travelledDistance:0}],entityCounters:{...run.entityCounters,enemy:id}}}return {...state,run}}case 'TICK':return {...state,run:stepCombat(state.run,action.delta)};case 'CLONE_UNIT':return cloneUnit(state);case 'MOVE_OR_MERGE':return resolveBoardDrop(state,action.sourceSlot,action.targetSlot);case 'DISCARD_UNIT':return discardUnit(state,action.unitId);case 'SKIP_ROUND':if(state.run.enemies.length||state.run.pendingSpawns)return state;return notify({...state,run:stepCombat({...state.run,round:{...state.run.round,remaining:0}},0)},'round-skipped');case 'REROLL_CARDS':if(!state.run.rerolls)return state;return notify({...state,run:{...offerCards({...state.run,rerolls:state.run.rerolls-1}),rerolls:state.run.rerolls-1}},'card-rerolled',{remaining:state.run.rerolls-1});case 'CHOOSE_CARD':if(!state.run.cardOffer.includes(action.cardId))return state;const card=cardDefinitions[action.cardId];if(card.kind==='아이템')return {...state,run:{...state.run,phase:'item-targeting',pendingCard:action.cardId}};return notify({...state,run:startNext({...state.run,cards:[...state.run.cards,{cardId:action.cardId,round:5}],activeRuleEffects:[...state.run.activeRuleEffects,action.cardId],freeCloneTickets:action.cardId==='free-clone'?state.run.freeCloneTickets+3:state.run.freeCloneTickets})},'card-applied',{cardTitle:card.title});case 'EQUIP_PENDING_ITEM':{const unit=state.run.units.find(u=>u.id===action.unitId);if(!unit||unit.item||!state.run.pendingCard)return state;const pending=state.run.pendingCard;return notify({...state,run:startNext({...state.run,units:state.run.units.map(u=>u.id===unit.id?{...u,item:pending}:u),cards:[...state.run.cards,{cardId:pending,round:5,unitId:unit.id}],pendingCard:undefined})},'item-attached',{unitName:'실험체'})}}}
const startNext=(run:GameStoreState['run'])=>{const d=roundDefinition(6);return {...run,phase:'combat' as const,cardOffer:[],round:{number:6,kind:d.kind,remaining:d.duration,started:true,spawnElapsed:0,spawned:0,total:d.total},pendingSpawns:d.total}}
